export type ApiResponse<T> = {
  success: boolean;
  message: string;
  data: T;
};

export type Pagination = {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
};

export type User = {
  id: string;
  name: string;
  email: string;
};

export type Contact = {
  _id: string;
  name: string;
  phone?: string;
  email?: string;
  note?: string;
  source?: "MANUAL" | "DEVICE_CONTACT";
  deviceContactId?: string;
  normalizedPhone?: string;
  lastUsedAt?: string;
  avatarColor?: string;
  createdAt: string;
  updatedAt: string;
};

export type LoanType = "GIVEN" | "TAKEN";
export type LoanStatus = "ACTIVE" | "PARTIALLY_PAID" | "COMPLETED" | "OVERDUE";
export type PaymentType = "RECEIVED" | "PAID";
export type PaymentMethod = "CASH" | "BANK" | "JAZZCASH" | "EASYPAISA" | "OTHER";
export type TransactionType = "INCOME" | "EXPENSE" | "LOAN_RECOVERY" | "LOAN_REPAYMENT";
export type GoalStatus = "ACTIVE" | "COMPLETED" | "ARCHIVED";

export type Loan = {
  _id: string;
  userId: string;
  contactId: string | Contact;
  type: LoanType;
  amount: number;
  paidAmount: number;
  remainingAmount: number;
  issueDate: string;
  dueDate?: string;
  status: LoanStatus;
  description?: string;
  createdAt: string;
  updatedAt: string;
};

export type Payment = {
  _id: string;
  userId: string;
  loanId: string | Loan;
  contactId: string | Contact;
  amount: number;
  type: PaymentType;
  method: PaymentMethod;
  paymentDate: string;
  note?: string;
  createdAt: string;
  updatedAt: string;
};

export type Category = {
  _id: string;
  userId?: string;
  name: string;
  type: "INCOME" | "EXPENSE";
  icon?: string;
  color?: string;
  isDefault: boolean;
  isActive: boolean;
  monthlyBudget?: number;
  createdAt: string;
  updatedAt: string;
};

export type Transaction = {
  _id: string;
  userId: string;
  type: TransactionType;
  amount: number;
  date: string;
  categoryId?: string | Category;
  source?: string;
  paymentMethod: PaymentMethod;
  note?: string;
  linkedLoanId?: string | Loan;
  linkedPaymentId?: string | Payment;
  linkedContactId?: string | Contact;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
};

export type Goal = {
  _id: string;
  userId: string;
  title: string;
  targetAmount: number;
  savedAmount: number;
  remainingAmount: number;
  progressPercent: number;
  status: GoalStatus;
  note?: string;
  completedAt?: string;
  createdAt: string;
  updatedAt: string;
};

export type GoalContribution = {
  _id: string;
  userId: string;
  goalId: string | Goal;
  amount: number;
  date: string;
  note?: string;
  createdAt: string;
  updatedAt: string;
};

export type AuthPayload = {
  user: User;
  token: string;
};

export type PaginatedContacts = {
  contacts: Contact[];
  pagination: Pagination;
};

export type PaginatedLoans = {
  loans: Loan[];
  pagination: Pagination;
};

export type PaginatedTransactions = {
  transactions: Transaction[];
  pagination: Pagination;
};

export type PaginatedGoals = {
  goals: Goal[];
  pagination: Pagination;
};

export type GoalDetail = {
  goal: Goal;
  contributions: GoalContribution[];
};

export type GoalSummary = {
  activeGoals: number;
  completedGoals: number;
  archivedGoals: number;
  totalTargetAmount: number;
  totalSavedAmount: number;
  totalRemainingAmount: number;
  nearestGoal?: Goal | null;
};

export type GoalMutationResponse = {
  goal: Goal;
  message?: string;
};

export type GoalContributionMutationResponse = {
  goal: Goal;
  contribution?: GoalContribution;
  id?: string;
  message?: string;
};

export type ContactBalanceSummary = {
  totalLoans: number;
  totalGiven: number;
  totalTaken: number;
  totalReceivedBack: number;
  totalPaidBack: number;
  netReceivable: number;
  netPayable: number;
  activeLoans: number;
  completedLoans: number;
  overdueLoans: number;
  overallBalance: number;
};

export type ContactDetail = {
  contact: Contact;
  summary: ContactBalanceSummary;
  recentLoans: Loan[];
};

export type LedgerTimelineItem = {
  id: string;
  kind: "LOAN" | "PAYMENT";
  date: string;
  amount: number;
  type: string;
  status?: LoanStatus;
  method?: PaymentMethod;
  description?: string;
  note?: string;
  remainingAmount?: number;
  createdAt: string;
};

export type ContactLedger = ContactDetail & {
  loans: Loan[];
  payments: Payment[];
  timeline: LedgerTimelineItem[];
};

export type LoanDetail = {
  loan: Loan;
  payments: Payment[];
};

export type PaymentMutationResponse = {
  payment?: Payment;
  loan: Loan;
  id?: string;
};

export type DashboardSummary = {
  totalLoanGiven: number;
  totalLoanTaken: number;
  totalReceivedBack: number;
  totalPaidBack: number;
  netReceivable: number;
  netPayable: number;
  overallBalance: number;
  activeLoans: number;
  completedLoans: number;
  overdueLoans: number;
};

export type MonthlyChartPoint = {
  month: string;
  given: number;
  taken: number;
  received: number;
  paid: number;
};

export type LoanTypeChartPoint = {
  name?: LoanType;
  type?: LoanType;
  amount: number;
  count?: number;
  remainingAmount?: number;
};

export type LoanStatusChartPoint = {
  status: LoanStatus;
  count: number;
  amount?: number;
  remainingAmount?: number;
};

export type TopContact = {
  contactId: string;
  contactName?: string;
  name?: string;
  phone?: string;
  totalAmount: number;
  remainingAmount: number;
  overallBalance?: number;
};

export type DeviceContactImportPayload = {
  deviceContactId?: string;
  name: string;
  phone?: string;
  emails?: string[];
  source?: "DEVICE_CONTACT";
};

export type ContactMatchResult = {
  contact: Contact | null;
  matchConfidence: number;
  reason: string;
};

export type DeviceContactImportResult = {
  contact: Contact;
  imported: boolean;
  duplicate: boolean;
  match: ContactMatchResult;
};

export type BulkDeviceContactImportResult = {
  importedCount: number;
  skippedCount: number;
  duplicateCount: number;
  contacts: Contact[];
  duplicates: Array<{ input: DeviceContactImportPayload; contact: Contact; reason: string }>;
};
