import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Edit3, ExternalLink, Trash2 } from "lucide-react-native";
import { Text, View } from "react-native";
import { api } from "../../api/client";
import { AmountText } from "../../components/AmountText";
import { AppButton } from "../../components/AppButton";
import { Screen } from "../../components/Screen";
import { ErrorState, LoadingState } from "../../components/StateViews";
import { RootStackParamList } from "../../navigation/types";
import { showAlert } from "../../providers/AlertProvider";
import { useAppTheme } from "../../providers/ThemeProvider";
import { categoryName, contactName, loanLabel, transactionTypeLabels } from "../../utils/finance";
import { getErrorMessage } from "../../utils/errors";
import { formatDateTime } from "../../utils/format";
import { fontFamily } from "../../utils/theme";

type Props = NativeStackScreenProps<RootStackParamList, "TransactionDetail">;

const DetailRow = ({ label, value }: { label: string; value?: string }) => (
  <View className="flex-row justify-between gap-4 border-b border-border py-3">
    <Text className="text-sm font-bold text-muted">{label}</Text>
    <Text className="flex-1 text-right text-sm font-bold text-dark">{value || "-"}</Text>
  </View>
);

export const TransactionDetailScreen = ({ navigation, route }: Props) => {
  const { theme } = useAppTheme();
  const queryClient = useQueryClient();
  const transactionQuery = useQuery({
    queryKey: ["transaction", route.params.transactionId],
    queryFn: () => api.getTransaction(route.params.transactionId),
  });

  const deleteMutation = useMutation({
    mutationFn: () => api.deleteTransaction(route.params.transactionId),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["transactions"] });
      await queryClient.invalidateQueries({ queryKey: ["dashboard"] });
      navigation.goBack();
    },
  });

  if (transactionQuery.isLoading) return <Screen><LoadingState label="Loading transaction..." /></Screen>;
  if (transactionQuery.isError) return <Screen><ErrorState message="Transaction load nahi ho saki." onRetry={transactionQuery.refetch} /></Screen>;

  const transaction = transactionQuery.data;
  if (!transaction) return null;
  const loanId = typeof transaction.linkedLoanId === "string" ? transaction.linkedLoanId : transaction.linkedLoanId?._id;

  const confirmDelete = () => {
    showAlert({
      title: "Delete transaction?",
      message: "Ye manual transaction remove ho jayegi.",
      buttons: [
        { text: "Cancel", style: "cancel" },
        { text: "Delete", style: "destructive", onPress: () => deleteMutation.mutate() },
      ],
    });
  };

  return (
    <Screen className="gap-5 pt-5">
      <View className="rounded-3xl border border-border bg-card p-5" style={theme.shadowSoft}>
        <Text className="text-xs font-bold uppercase text-muted">{transactionTypeLabels[transaction.type]}</Text>
        <AmountText amount={transaction.amount} className="mt-2 text-3xl font-bold text-dark" style={{ fontFamily: fontFamily.bold }} />
        <Text className="mt-1 text-sm font-semibold text-muted">{formatDateTime(transaction.date)}</Text>
      </View>

      <View className="rounded-3xl border border-border bg-card p-5" style={theme.shadowSoft}>
        <DetailRow label="Category / Source" value={transaction.source || categoryName(transaction.categoryId)} />
        <DetailRow label="Payment Method" value={transaction.paymentMethod} />
        <DetailRow label="Contact" value={contactName(transaction.linkedContactId)} />
        <DetailRow label="Loan" value={loanLabel(transaction.linkedLoanId)} />
        <DetailRow label="Auto Generated" value={transaction.isAutoGenerated ? "Yes" : "No"} />
        <DetailRow label="Note" value={transaction.note} />
      </View>

      {transaction.isAutoGenerated ? (
        <Text className="rounded-2xl bg-background-soft p-4 text-sm font-semibold text-muted">
          Auto transaction source loan payment se update hoti hai.
        </Text>
      ) : (
        <View className="flex-row gap-3">
          <View className="flex-1">
            <AppButton title="Edit" icon={Edit3} variant="secondary" onPress={() => navigation.navigate("AddTransaction", { transactionId: transaction._id })} />
          </View>
          <View className="flex-1">
            <AppButton title="Delete" icon={Trash2} variant="danger" loading={deleteMutation.isPending} onPress={confirmDelete} />
          </View>
        </View>
      )}

      {loanId ? <AppButton title="Open Linked Loan" icon={ExternalLink} onPress={() => navigation.navigate("LoanDetail", { loanId })} /> : null}
      {deleteMutation.isError ? <Text className="text-sm font-semibold text-danger">{getErrorMessage(deleteMutation.error)}</Text> : null}
    </Screen>
  );
};
