import React, { useEffect, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { AlertCircle, ArrowLeft, ReceiptText, Save } from "lucide-react";
import Button from "../../components/common/Button";
import Card from "../../components/common/Card";
import Input from "../../components/common/Input";
import LoadingState from "../../components/common/LoadingState";
import Select from "../../components/common/Select";
import { ROUTES } from "../../config/routes.config";
import { useTransactions } from "../../hooks/useTransactions";

const transactionSchema = z.object({
  amount: z.coerce.number().min(1, "Amount must be greater than 0"),
  type: z.enum(["INCOME", "EXPENSE"]),
  categoryId: z.string().min(1, "Please select a category"),
  paymentMethod: z.enum(["CASH", "BANK", "JAZZCASH", "EASYPAISA", "OTHER"]),
  date: z.string().min(1, "Date is required"),
  source: z.string().max(120, "Source is too long").optional(),
  note: z.string().max(500, "Note is too long").optional(),
});

type TransactionFormInputs = z.infer<typeof transactionSchema>;

const toDateInput = (value?: string) => {
  if (!value) return new Date().toISOString().split("T")[0];
  return new Date(value).toISOString().split("T")[0];
};

export const AddTransaction: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id?: string }>();
  const [searchParams] = useSearchParams();
  const [formError, setFormError] = useState<string | null>(null);
  const isEditing = Boolean(id);

  const {
    transactionDetail,
    createTransaction,
    updateTransaction,
    isCreating,
    isUpdating,
    categories,
    isLoading,
  } = useTransactions(id);

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    reset,
    formState: { errors },
  } = useForm<TransactionFormInputs>({
    resolver: zodResolver(transactionSchema) as any,
    defaultValues: {
      type: searchParams.get("type") === "INCOME" ? "INCOME" : "EXPENSE",
      paymentMethod: "CASH",
      date: new Date().toISOString().split("T")[0],
      categoryId: "",
      source: "",
      note: "",
    },
  });

  useEffect(() => {
    if (!transactionDetail || !isEditing) return;
    if (transactionDetail.type !== "INCOME" && transactionDetail.type !== "EXPENSE") return;
    reset({
      type: transactionDetail.type,
      amount: transactionDetail.amount,
      categoryId: typeof transactionDetail.categoryId === "string" ? transactionDetail.categoryId : transactionDetail.categoryId?._id || "",
      paymentMethod: transactionDetail.paymentMethod,
      date: toDateInput(transactionDetail.date),
      source: transactionDetail.source || "",
      note: transactionDetail.note || "",
    });
  }, [isEditing, reset, transactionDetail]);

  const selectedType = watch("type");
  const filteredCategories = (categories || []).filter((category) => category.type === selectedType && category.isActive !== false);
  const saving = isCreating || isUpdating;
  const cannotEdit = isEditing && transactionDetail?.isAutoGenerated;

  const onSubmit = async (data: TransactionFormInputs) => {
    setFormError(null);
    const payload = {
      amount: Number(data.amount),
      type: data.type,
      categoryId: data.categoryId,
      paymentMethod: data.paymentMethod,
      date: data.date,
      source: data.source || undefined,
      note: data.note || undefined,
    };

    try {
      if (isEditing && id) {
        await updateTransaction({ id, payload });
        navigate(ROUTES.TRANSACTION_DETAIL.replace(":id", id));
      } else {
        await createTransaction(payload);
        navigate(ROUTES.EXPENSES);
      }
    } catch (err: any) {
      setFormError(err.response?.data?.message || "Failed to save transaction.");
    }
  };

  if (isEditing && isLoading) {
    return <LoadingState message="Loading transaction..." />;
  }

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div className="flex items-center gap-3">
        <button
          onClick={() => navigate(-1)}
          className="rounded-lg border border-transparent p-1.5 text-appMuted transition-all hover:border-appBorder hover:bg-appBgSoft hover:text-appText"
          aria-label="Go back"
        >
          <ArrowLeft className="h-4 w-4" />
        </button>
        <div className="flex min-w-0 items-center gap-3">
          <div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-appBorder bg-appCard text-appPrimary shadow-level1">
            <ReceiptText className="h-5 w-5" />
          </div>
          <div>
            <p className="page-kicker">{isEditing ? "Edit record" : "New record"}</p>
            <h1 className="text-2xl font-semibold leading-8 text-appText">
              {isEditing ? "Edit Transaction" : selectedType === "INCOME" ? "Add Income" : "Add Expense"}
            </h1>
            <p className="mt-1 text-sm font-normal text-appTextSecondary">Record manual income and expense entries for your ledger.</p>
          </div>
        </div>
      </div>

      <Card>
        {cannotEdit ? (
          <div className="rounded-lg border border-appWarning/25 bg-appWarning/10 p-4 text-sm font-medium text-appText">
            Auto-generated loan transactions must be changed from their source payment.
          </div>
        ) : (
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
            {formError && (
              <div className="flex items-center gap-2 rounded-lg border border-appDanger/25 bg-appDanger/10 p-3 text-sm font-medium text-appDanger">
                <AlertCircle className="h-4 w-4 shrink-0" />
                <span>{formError}</span>
              </div>
            )}

            <div className="grid grid-cols-2 gap-2 rounded-lg bg-appBgSoft p-1">
              <button
                type="button"
                onClick={() => {
                  setValue("type", "EXPENSE");
                  setValue("categoryId", "");
                }}
                className={`rounded-md py-2 text-sm font-medium transition-all ${
                  selectedType === "EXPENSE" ? "bg-appDanger text-white shadow-sm" : "text-appMuted hover:text-appText"
                }`}
              >
                Expense
              </button>
              <button
                type="button"
                onClick={() => {
                  setValue("type", "INCOME");
                  setValue("categoryId", "");
                }}
                className={`rounded-md py-2 text-sm font-medium transition-all ${
                  selectedType === "INCOME" ? "bg-appSuccess text-white shadow-sm" : "text-appMuted hover:text-appText"
                }`}
              >
                Income
              </button>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <Input label="Amount (PKR)" type="number" placeholder="0" error={errors.amount?.message} {...register("amount")} />
              <Input label="Date" type="date" error={errors.date?.message} {...register("date")} />
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <Select
                label="Category"
                value={watch("categoryId") || ""}
                onChange={(event) => setValue("categoryId", event.target.value)}
                error={errors.categoryId?.message}
                options={[
                  { label: "Choose category...", value: "" },
                  ...filteredCategories.map((category) => ({ label: category.name, value: category._id })),
                ]}
              />
              <Select
                label="Payment Method"
                error={errors.paymentMethod?.message}
                {...register("paymentMethod")}
                options={[
                  { label: "Cash", value: "CASH" },
                  { label: "Bank", value: "BANK" },
                  { label: "JazzCash", value: "JAZZCASH" },
                  { label: "EasyPaisa", value: "EASYPAISA" },
                  { label: "Other", value: "OTHER" },
                ]}
              />
            </div>

            <Input
              label="Source"
              placeholder={selectedType === "INCOME" ? "Salary, freelance, gift..." : "Groceries, fuel, utility bill..."}
              error={errors.source?.message}
              {...register("source")}
            />

            <Input label="Note" placeholder="Optional detail" error={errors.note?.message} {...register("note")} />

            <div className="flex flex-col-reverse gap-2 border-t border-appBorder pt-5 sm:flex-row sm:justify-end">
              <Button type="button" variant="outline" onClick={() => navigate(-1)} disabled={saving}>
                Cancel
              </Button>
              <Button type="submit" variant="primary" isLoading={saving} leftIcon={<Save className="h-4 w-4" />}>
                {isEditing ? "Save Changes" : "Save Transaction"}
              </Button>
            </div>
          </form>
        )}
      </Card>
    </div>
  );
};

export default AddTransaction;
