import React, { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { ArrowLeft, Trash2, Calendar, CreditCard, Layers, User, FileText, Edit3 } from "lucide-react";
import Card from "../../components/common/Card";
import Button from "../../components/common/Button";
import Badge from "../../components/common/Badge";
import AmountText from "../../components/common/AmountText";
import LoadingState from "../../components/common/LoadingState";
import ConfirmDialog from "../../components/common/ConfirmDialog";
import { useTransactions } from "../../hooks/useTransactions";
import { ROUTES } from "../../config/routes.config";

export const TransactionDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [deleteOpen, setDeleteOpen] = useState(false);

  // Query detail
  const { transactionDetail: tx, isLoading, deleteTransaction, isDeleting } = useTransactions(id);

  const confirmDelete = async () => {
    if (id) {
      try {
        await deleteTransaction(id);
        navigate(ROUTES.EXPENSES);
      } catch (err) {
        alert("Failed to delete transaction.");
      }
    }
  };

  if (isLoading) {
    return <LoadingState message="Loading money log details..." />;
  }

  if (!tx) {
    return <div className="py-10 text-center text-sm text-appMuted">Transaction record not found.</div>;
  }

  const isIncome = tx.type === "INCOME" || tx.type === "LOAN_RECOVERY";
  const catName = typeof tx.categoryId === "object" && tx.categoryId ? tx.categoryId.name : "General";
  const contactName = typeof tx.linkedContactId === "object" && tx.linkedContactId ? tx.linkedContactId.name : null;

  return (
    <div className="max-w-xl mx-auto space-y-6">
      {/* Back button */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate(-1)}
            className="text-appMuted hover:text-appText p-1.5 rounded-lg hover:bg-appBgSoft border border-transparent hover:border-appBorder transition-all"
          >
            <ArrowLeft className="h-5 w-5" />
          </button>
          <div>
            <h1 className="text-lg font-semibold text-appText">Transaction Record</h1>
            <p className="text-xs text-appMuted">Detailed view of logged cash flow ledger entry.</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {!tx.isAutoGenerated && (tx.type === "INCOME" || tx.type === "EXPENSE") ? (
            <Button
              variant="secondary"
              size="sm"
              onClick={() => navigate(ROUTES.EDIT_TRANSACTION.replace(":id", tx._id))}
              leftIcon={<Edit3 className="h-4 w-4" />}
            >
              Edit
            </Button>
          ) : null}
          <Button
            variant="danger"
            size="sm"
            onClick={() => setDeleteOpen(true)}
            leftIcon={<Trash2 className="h-4 w-4" />}
            disabled={tx.isAutoGenerated}
          >
            Delete
          </Button>
        </div>
      </div>

      {/* Main card representation */}
      <Card variant="bordered" className="space-y-5">
        {/* Header showing large amount */}
        <div className="border-b border-appBorder py-5 text-center">
          <span className="block text-xs font-semibold uppercase tracking-[0.05em] text-appMuted">Logged Amount</span>
          <h2 className={`mt-2 text-3xl font-semibold ${isIncome ? "text-appSuccess" : "text-appDanger"}`}>
            {isIncome ? "+" : "-"}<AmountText amount={tx.amount} />
          </h2>
          <span className="inline-block mt-3">
            <Badge variant={isIncome ? "success" : "danger"}>
              {tx.type}
            </Badge>
          </span>
        </div>

        {/* Detailed items list */}
        <div className="space-y-3 text-xs sm:text-sm">
          <div className="flex items-center justify-between border-b border-appBorder py-2">
            <div className="flex items-center gap-2 text-appMuted">
              <FileText className="h-4 w-4" />
              <span>Description / Note</span>
            </div>
            <span className="font-medium text-appText">{tx.note || catName}</span>
          </div>

          <div className="flex items-center justify-between border-b border-appBorder py-2">
            <div className="flex items-center gap-2 text-appMuted">
              <Layers className="h-4 w-4 text-appPrimary" />
              <span>Category Envelope</span>
            </div>
            <span className="font-medium text-appText">{catName}</span>
          </div>

          <div className="flex items-center justify-between border-b border-appBorder py-2">
            <div className="flex items-center gap-2 text-appMuted">
              <Calendar className="h-4 w-4" />
              <span>Transaction Date</span>
            </div>
            <span className="font-medium text-appText">{new Date(tx.date || tx.createdAt).toLocaleDateString()}</span>
          </div>

          <div className="flex items-center justify-between border-b border-appBorder py-2">
            <div className="flex items-center gap-2 text-appMuted">
              <CreditCard className="h-4 w-4 text-appWarning" />
              <span>Payment Method</span>
            </div>
            <span className="rounded-md border border-appBorder bg-appBgSoft px-2 py-0.5 text-xs font-medium text-appText">{tx.paymentMethod}</span>
          </div>

          {contactName && (
            <div className="flex items-center justify-between border-b border-appBorder py-2">
              <div className="flex items-center gap-2 text-appMuted">
                <User className="h-4 w-4 text-appSuccess" />
                <span>Linked Contact</span>
              </div>
              <span className="font-medium text-appText">{contactName}</span>
            </div>
          )}
        </div>
      </Card>

      {/* Confirmation dialog */}
      <ConfirmDialog
        isOpen={deleteOpen}
        onClose={() => setDeleteOpen(false)}
        onConfirm={confirmDelete}
        title="Delete Transaction"
        message="Are you sure you want to delete this transaction? This only applies to manual income and expense records."
        confirmText={isDeleting ? "Deleting..." : "Delete"}
        isDestructive={true}
        isLoading={isDeleting}
      />
    </div>
  );
};

export default TransactionDetail;
