import { ArrowDownLeft, ArrowUpRight, CalendarDays, LockKeyhole } from "lucide-react-native";
import { Text, TouchableOpacity, View } from "react-native";
import { Transaction } from "../api/types";
import { useAppTheme } from "../providers/ThemeProvider";
import { categoryName, contactName, transactionTypeLabels, transactionTypeTone } from "../utils/finance";
import { formatCurrency } from "../utils/format";
import { fontFamily } from "../utils/theme";

type TransactionCardProps = {
  transaction: Transaction;
  onPress?: () => void;
  showDivider?: boolean;
};

const shortDate = (date?: string | Date | null) => {
  if (!date) return "-";

  return new Intl.DateTimeFormat("en", {
    day: "numeric",
    month: "short",
  }).format(new Date(date));
};

const iconLabel = (label: string) => label.trim().charAt(0).toUpperCase() || "T";

export const TransactionCard = ({ transaction, onPress, showDivider = true }: TransactionCardProps) => {
  const { theme } = useAppTheme();
  const tone = transactionTypeTone[transaction.type];
  const positive = tone === "inflow";
  const Icon = positive ? ArrowDownLeft : ArrowUpRight;
  const contact = contactName(transaction.linkedContactId);
  const label = transaction.source || categoryName(transaction.categoryId) || contact || transactionTypeLabels[transaction.type];
  const amountText = `${positive ? "+" : "-"}${formatCurrency(transaction.amount).replace(/\u00a0/g, " ")}`;

  return (
    <TouchableOpacity activeOpacity={0.86} onPress={onPress} disabled={!onPress}>
      <View className="flex-row items-center gap-3 py-3">
        <View
          style={{
            height: 42,
            width: 42,
            borderRadius: 8,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: positive ? theme.mint : theme.peach,
          }}
        >
          {transaction.categoryId ? (
            <Text style={{ color: positive ? theme.success : theme.danger, fontFamily: fontFamily.semiBold, fontSize: 14 }}>
              {iconLabel(label)}
            </Text>
          ) : (
            <Icon color={positive ? theme.success : theme.danger} size={19} />
          )}
        </View>

        <View className="min-w-0 flex-1">
          <View className="flex-row items-center gap-2">
            <Text numberOfLines={1} style={{ color: theme.text, fontFamily: fontFamily.semiBold, fontSize: 15 }}>
              {label}
            </Text>
            {transaction.isAutoGenerated ? (
              <View className="flex-row items-center gap-1 bg-background-soft px-2 py-1" style={{ borderRadius: 6 }}>
                <LockKeyhole color={theme.muted} size={9} />
                <Text className="text-[9px] font-semibold uppercase text-muted">Auto</Text>
              </View>
            ) : null}
          </View>
          <Text numberOfLines={1} style={{ color: theme.muted, fontFamily: fontFamily.regular, fontSize: 13, marginTop: 4 }}>
            {shortDate(transaction.date)} · {transaction.note || transaction.paymentMethod || transactionTypeLabels[transaction.type]}
          </Text>
        </View>

        <View className="items-end">
          <Text
            numberOfLines={1}
            adjustsFontSizeToFit
            minimumFontScale={0.76}
            style={{
              color: positive ? theme.success : theme.danger,
              fontFamily: fontFamily.semiBold,
              fontSize: 16,
              maxWidth: 112,
            }}
          >
            {amountText}
          </Text>
          <CalendarDays color={theme.muted} size={13} style={{ marginTop: 5 }} />
        </View>
      </View>
      {showDivider ? <View style={{ height: 1, backgroundColor: theme.border, opacity: 0.65, marginLeft: 55 }} /> : null}
    </TouchableOpacity>
  );
};
