import { ArrowDownLeft, ArrowUpRight, LockKeyhole, ReceiptText } from "lucide-react-native";
import { Text, TouchableOpacity, View } from "react-native";
import { Transaction } from "../api/types";
import { useAppTheme } from "../providers/ThemeProvider";
import { categoryName, contactName, transactionTypeLabels, transactionTypeTone } from "../utils/finance";
import { formatDate } from "../utils/format";
import { fontFamily } from "../utils/theme";
import { AmountText } from "./AmountText";

type TransactionCardProps = {
  transaction: Transaction;
  onPress?: () => void;
};

export const TransactionCard = ({ transaction, onPress }: TransactionCardProps) => {
  const { theme } = useAppTheme();
  const tone = transactionTypeTone[transaction.type];
  const positive = tone === "inflow";
  const Icon = positive ? ArrowDownLeft : ArrowUpRight;
  const contact = contactName(transaction.linkedContactId);
  const label = transaction.source || categoryName(transaction.categoryId) || contact || transactionTypeLabels[transaction.type];

  return (
    <TouchableOpacity
      activeOpacity={0.86}
      onPress={onPress}
      disabled={!onPress}
      className="rounded-3xl border border-border bg-card p-4"
      style={theme.shadowSoft}
    >
      <View className="flex-row items-center gap-4">
        <View className="h-12 w-12 items-center justify-center rounded-2xl bg-background-soft">
          <Icon color={positive ? theme.success : theme.danger} size={22} />
        </View>
        <View className="flex-1">
          <View className="flex-row flex-wrap items-center gap-2">
            <Text className="text-base font-black text-dark" style={{ fontFamily: fontFamily.extraBold }}>
              {label}
            </Text>
            {transaction.isAutoGenerated ? (
              <View className="flex-row items-center gap-1 rounded-full bg-background-soft px-2 py-1">
                <LockKeyhole color={theme.muted} size={10} />
                <Text className="text-[10px] font-black uppercase text-muted">Auto</Text>
              </View>
            ) : null}
          </View>
          <Text className="mt-1 text-xs font-semibold text-muted">
            {transactionTypeLabels[transaction.type]} · {transaction.paymentMethod} · {formatDate(transaction.date)}
          </Text>
          {contact ? <Text className="mt-1 text-xs font-semibold text-muted">{contact}</Text> : null}
          {transaction.note ? <Text numberOfLines={1} className="mt-1 text-xs font-semibold text-muted">{transaction.note}</Text> : null}
        </View>
        <View className="items-end">
          <AmountText
            amount={transaction.amount}
            prefix={positive ? "+" : "-"}
            className="text-sm font-black"
            style={{ color: positive ? theme.success : theme.danger, fontFamily: fontFamily.extraBold }}
            hiddenLabel={`${positive ? "+" : "-"}Rs. ****`}
          />
          <ReceiptText color={theme.muted} size={16} />
        </View>
      </View>
    </TouchableOpacity>
  );
};
