import mongoose, { Document, Schema, Types } from "mongoose";
import { PaymentMethod } from "../../constants/enums";

export const TRANSACTION_TYPES = ["INCOME", "EXPENSE", "LOAN_RECOVERY", "LOAN_REPAYMENT"] as const;
export type TransactionType = (typeof TRANSACTION_TYPES)[number];

export interface ITransaction extends Document {
  userId: Types.ObjectId;
  type: TransactionType;
  amount: number;
  date: Date;
  categoryId?: Types.ObjectId;
  source?: string;
  paymentMethod: PaymentMethod;
  note?: string;
  linkedLoanId?: Types.ObjectId;
  linkedPaymentId?: Types.ObjectId;
  linkedContactId?: Types.ObjectId;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const transactionSchema = new Schema<ITransaction>(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
    type: { type: String, enum: TRANSACTION_TYPES, required: true, index: true },
    amount: { type: Number, required: true, min: 0.01 },
    date: { type: Date, required: true, default: Date.now, index: true },
    categoryId: { type: Schema.Types.ObjectId, ref: "Category", index: true },
    source: { type: String, trim: true, maxlength: 120 },
    paymentMethod: { type: String, enum: Object.values(PaymentMethod), required: true, default: PaymentMethod.CASH, index: true },
    note: { type: String, trim: true, maxlength: 500 },
    linkedLoanId: { type: Schema.Types.ObjectId, ref: "Loan", index: true },
    linkedPaymentId: { type: Schema.Types.ObjectId, ref: "Payment", index: true },
    linkedContactId: { type: Schema.Types.ObjectId, ref: "Contact", index: true },
    isAutoGenerated: { type: Boolean, default: false, index: true },
  },
  { timestamps: true },
);

transactionSchema.index({ userId: 1, date: -1 });
transactionSchema.index({ userId: 1, type: 1, date: -1 });
transactionSchema.index({ userId: 1, linkedPaymentId: 1 }, { sparse: true });

export const TransactionModel = mongoose.model<ITransaction>("Transaction", transactionSchema);
