import { Types } from "mongoose";
import { LoanType, PaymentMethod } from "../../constants/enums";
import { ApiError } from "../../utils/apiError";
import { buildPaginationMeta } from "../../utils/pagination";
import { auditLogService } from "../audit/audit-log.service";
import { CategoryModel } from "../categories/category.model";
import { ILoan } from "../loans/loan.model";
import { IPayment } from "../payments/payment.model";
import { TransactionModel, TransactionType } from "./transaction.model";

const toObjectId = (id: string | Types.ObjectId) => typeof id === "string" ? new Types.ObjectId(id) : id;

const normalize = (payload: Record<string, unknown>) => {
  const next = { ...payload };
  if (next.note === "") next.note = undefined;
  if (next.source === "") next.source = undefined;
  return next;
};

const validateCategory = async (userId: string, type: TransactionType, categoryId?: string) => {
  if (!categoryId) return undefined;
  const expectedType = type === "INCOME" ? "INCOME" : type === "EXPENSE" ? "EXPENSE" : undefined;
  if (!expectedType) throw new ApiError(400, "This transaction type does not support categories");
  const category = await CategoryModel.findOne({ _id: categoryId, userId: toObjectId(userId), type: expectedType, isActive: true });
  if (!category) throw new ApiError(400, `${expectedType.toLowerCase()} category not found`);
  return category._id;
};

export const transactionService = {
  async create(userId: string, payload: {
    type: "INCOME" | "EXPENSE";
    amount: number;
    date: Date;
    categoryId?: string;
    source?: string;
    paymentMethod: PaymentMethod;
    note?: string;
  }) {
    const categoryId = await validateCategory(userId, payload.type, payload.categoryId);
    return TransactionModel.create({
      ...normalize(payload),
      userId: toObjectId(userId),
      categoryId,
      isAutoGenerated: false,
    });
  },

  async list(userId: string, filters: {
    type?: TransactionType;
    categoryId?: string;
    paymentMethod?: PaymentMethod;
    dateFrom?: Date;
    dateTo?: Date;
    minAmount?: number;
    maxAmount?: number;
    search?: string;
    linkedContactId?: string;
    page: number;
    limit: number;
    sortBy: "date" | "amount" | "createdAt";
    sortOrder: "asc" | "desc";
  }) {
    const query: Record<string, unknown> = { userId: toObjectId(userId) };
    if (filters.type) query.type = filters.type;
    if (filters.categoryId) query.categoryId = toObjectId(filters.categoryId);
    if (filters.paymentMethod) query.paymentMethod = filters.paymentMethod;
    if (filters.linkedContactId) query.linkedContactId = toObjectId(filters.linkedContactId);
    if (filters.minAmount !== undefined || filters.maxAmount !== undefined) {
      query.amount = {
        ...(filters.minAmount !== undefined ? { $gte: filters.minAmount } : {}),
        ...(filters.maxAmount !== undefined ? { $lte: filters.maxAmount } : {}),
      };
    }
    if (filters.dateFrom || filters.dateTo) {
      const dateFrom = filters.dateFrom ? new Date(filters.dateFrom) : undefined;
      const dateTo = filters.dateTo ? new Date(filters.dateTo) : undefined;
      if (dateFrom) dateFrom.setHours(0, 0, 0, 0);
      if (dateTo) dateTo.setHours(23, 59, 59, 999);
      query.date = {
        ...(dateFrom ? { $gte: dateFrom } : {}),
        ...(dateTo ? { $lte: dateTo } : {}),
      };
    }
    if (filters.search) {
      query.$or = [
        { note: new RegExp(filters.search, "i") },
        { source: new RegExp(filters.search, "i") },
      ];
    }
    const limit = Math.min(filters.limit, 100);
    const [transactions, total] = await Promise.all([
      TransactionModel.find(query)
        .populate("categoryId", "name type icon color")
        .populate("linkedContactId", "name phone")
        .populate("linkedLoanId", "amount remainingAmount status type")
        .sort({ [filters.sortBy]: filters.sortOrder === "asc" ? 1 : -1, createdAt: -1 })
        .skip((filters.page - 1) * limit)
        .limit(limit),
      TransactionModel.countDocuments(query),
    ]);
    return { transactions, pagination: buildPaginationMeta(filters.page, limit, total) };
  },

  async get(userId: string, id: string) {
    const transaction = await TransactionModel.findOne({ _id: id, userId: toObjectId(userId) })
      .populate("categoryId", "name type icon color")
      .populate("linkedContactId", "name phone")
      .populate("linkedLoanId", "amount paidAmount remainingAmount status type")
      .populate("linkedPaymentId");
    if (!transaction) throw new ApiError(404, "Transaction not found");
    return transaction;
  },

  async update(userId: string, id: string, payload: Record<string, unknown>) {
    const transaction = await TransactionModel.findOne({ _id: id, userId: toObjectId(userId) });
    if (!transaction) throw new ApiError(404, "Transaction not found");
    if (transaction.isAutoGenerated) throw new ApiError(400, "Auto-generated transactions must be changed from their source record");
    const nextType = (payload.type as TransactionType | undefined) || transaction.type;
    if (nextType !== "INCOME" && nextType !== "EXPENSE") {
      throw new ApiError(400, "Loan recovery/repayment transactions are auto-generated only");
    }
    const categoryId = await validateCategory(userId, nextType, payload.categoryId as string | undefined);
    transaction.set({
      ...normalize(payload),
      ...(categoryId ? { categoryId } : {}),
    });
    await transaction.save();
    return transaction;
  },

  async delete(userId: string, id: string) {
    const transaction = await TransactionModel.findOne({ _id: id, userId: toObjectId(userId) });
    if (!transaction) throw new ApiError(404, "Transaction not found");
    if (transaction.isAutoGenerated) throw new ApiError(400, "Auto-generated transactions must be deleted from their source record");
    await transaction.deleteOne();
    return { id };
  },

  async upsertLoanPaymentTransaction(userId: string, payment: IPayment, loan: ILoan) {
    const type = loan.type === LoanType.GIVEN ? "LOAN_RECOVERY" : "LOAN_REPAYMENT";
    const transaction = await TransactionModel.findOneAndUpdate(
      { userId: toObjectId(userId), linkedPaymentId: payment._id },
      {
        $set: {
          userId: toObjectId(userId),
          type,
          amount: payment.amount,
          date: payment.paymentDate,
          source: loan.type === LoanType.GIVEN ? "Loan recovery" : "Loan repayment",
          paymentMethod: payment.method,
          note: payment.note,
          linkedLoanId: payment.loanId,
          linkedPaymentId: payment._id,
          linkedContactId: payment.contactId,
          isAutoGenerated: true,
        },
      },
      { upsert: true, new: true, setDefaultsOnInsert: true },
    );
    await auditLogService.record({
      userId,
      action: transaction.createdAt.getTime() === transaction.updatedAt.getTime() ? "AUTO_TRANSACTION_CREATED" : "AUTO_TRANSACTION_UPDATED",
      entityType: "TRANSACTION",
      entityId: transaction._id.toString(),
      newValue: transaction.toObject(),
    });
    return transaction;
  },

  async deleteByPayment(userId: string, paymentId: string) {
    const transaction = await TransactionModel.findOneAndDelete({ userId: toObjectId(userId), linkedPaymentId: toObjectId(paymentId) });
    if (transaction) {
      await auditLogService.record({
        userId,
        action: "AUTO_TRANSACTION_DELETED",
        entityType: "TRANSACTION",
        entityId: transaction._id.toString(),
        oldValue: transaction.toObject(),
      });
    }
    return transaction;
  },

};
